"""Generate a fully self-contained dashboard HTML from run artifacts.

No external dependencies: charts are hand-rolled canvas; data is embedded as
JSON so the file works offline via file://.
"""
from __future__ import annotations

import json
import os


_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Autonomous Startup Sim - __RUN_NAME__</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root{--bg:#0d1117;--panel:#161b22;--edge:#21262d;--txt:#c9d1d9;--dim:#8b949e;
        --acc:#58a6ff;--good:#3fb950;--bad:#f85149;--warn:#d29922;}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--txt);
       font:14px/1.45 -apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif}
  .wrap{max-width:1200px;margin:0 auto;padding:20px}
  h1{font-size:22px;margin:4px 0 2px} h2{font-size:16px;margin:22px 0 8px;color:var(--acc)}
  .sub{color:var(--dim);font-size:13px;margin-bottom:16px}
  .grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px}
  .card{background:var(--panel);border:1px solid var(--edge);border-radius:8px;padding:12px}
  .card .k{color:var(--dim);font-size:11px;text-transform:uppercase;letter-spacing:.06em}
  .card .v{font-size:20px;font-weight:600;margin-top:3px;font-variant-numeric:tabular-nums}
  .card .s{font-size:11px;color:var(--dim);margin-top:2px}
  .good{color:var(--good)} .bad{color:var(--bad)} .warn{color:var(--warn)}
  canvas{width:100%;height:240px;display:block;background:var(--panel);
         border:1px solid var(--edge);border-radius:8px}
  table{border-collapse:collapse;width:100%;font-size:13px}
  th,td{text-align:left;padding:6px 8px;border-bottom:1px solid var(--edge)}
  th{color:var(--dim);font-weight:500;font-size:11px;text-transform:uppercase}
  tr:hover td{background:#1c2129}
  .pill{display:inline-block;padding:1px 8px;border-radius:10px;font-size:11px;font-weight:600}
  .pill.success{background:#12351d;color:var(--good)} .pill.fail{background:#3d1418;color:var(--bad)}
  .pill.partial{background:#372a12;color:var(--warn)} .pill.untracked{background:#232a33;color:var(--dim)}
  details{margin:6px 0} summary{cursor:pointer;color:var(--acc)}
  pre{white-space:pre-wrap;background:var(--panel);padding:10px;border-radius:6px;
      border:1px solid var(--edge);font-size:12px}
  .tabs{display:flex;gap:6px;margin:18px 0 0}
  .tabs button{background:var(--panel);color:var(--txt);border:1px solid var(--edge);
               padding:7px 14px;border-radius:6px 6px 0 0;cursor:pointer;font-size:13px}
  .tabs button.on{background:var(--bg);color:var(--acc);border-bottom-color:var(--bg)}
</style>
</head>
<body><div class="wrap">
<h1 id=title></h1><div class=sub id=subline></div>
<div class=tabs id=tabs></div>
<div id=views></div>
<div class=sub style="margin-top:30px">Generated by autonomous-startup-sim -
all numbers produced by the simulation engine; nothing is scripted.</div>
</div>
<script>
const DATA = __DATA__;
const inr = x => { if(x==null) return 'n/a'; const s=x<0?'-':'';x=Math.abs(x);
  if(x>=1e7) return s+'\u20B9'+(x/1e7).toFixed(2)+'Cr';
  if(x>=1e5) return s+'\u20B9'+(x/1e5).toFixed(2)+'L';
  return s+'\u20B9'+Math.round(x).toLocaleString('en-IN'); };
const pct = x => x==null?'n/a':(x*100).toFixed(0)+'%';
const el = (h)=>{const d=document.createElement('div');d.innerHTML=h;return d.firstElementChild;};

// ---------- charting ----------
function lineChart(canvas, series, opts={}){
  const dpr = window.devicePixelRatio||1;
  const W = canvas.clientWidth, H = canvas.clientHeight||240;
  canvas.width=W*dpr; canvas.height=H*dpr;
  const g = canvas.getContext('2d'); g.scale(dpr,dpr);
  const padL=64,padR=12,padT=12,padB=22;
  const iw=W-padL-padR, ih=H-padT-padB;
  let vmax=-Infinity,vmin=Infinity,xmax=0;
  for(const s of series){for(const p of s.points){
    if(p[1]!=null){vmax=Math.max(vmax,p[1]);vmin=Math.min(vmin,p[1]);}
    xmax=Math.max(xmax,p[0]);}}
  if(opts.zero)vmin=Math.min(0,vmin);
  if(!isFinite(vmin)){return;} if(vmax===vmin)vmax=vmin+1;
  const X=x=>padL+iw*(x/xmax), Y=v=>padT+ih*(1-(v-vmin)/(vmax-vmin));
  // grid
  g.strokeStyle='#21262d';g.fillStyle='#8b949e';g.font='10px sans-serif';
  for(let i=0;i<=4;i++){const v=vmin+(vmax-vmin)*i/4,y=Y(v);
    g.beginPath();g.moveTo(padL,y);g.lineTo(W-padR,y);g.stroke();
    g.fillText(opts.fmt?opts.fmt(v):Math.round(v),4,y+3);}
  for(const s of series){
    g.strokeStyle=s.color;g.lineWidth=1.6;g.beginPath();let started=false;
    for(const [x,v] of s.points){ if(v==null)continue;
      const px=X(x),py=Y(v);
      if(!started){g.moveTo(px,py);started=true;}else g.lineTo(px,py);}
    g.stroke();
    if(s.label){const last=s.points.filter(p=>p[1]!=null).pop();
      g.fillStyle=s.color;g.fillText(s.label,X(last[0])-g.measureText(s.label).width-2,Y(last[1])-5);}
  }
  g.fillStyle='#8b949e';
  g.fillText('day '+xmax, W-padR-40, H-6);
}

// ---------- views ----------
const V = {};
function card(k,v,s,cls){return `<div class=card><div class=k>${k}</div>
  <div class="v ${cls||''}">${v}</div><div class=s>${s||''}</div></div>`;}

V.overview = () => {
  const f=DATA.final,h=DATA.kpi_series,last=h[h.length-1];
  const firstMRR=h.find(x=>x.mrr>0);
  let html='<h2>Key metrics</h2><div class=grid>';
  html+=card('Cash',inr(f.cash), DATA.alive?'operating':'INSOLVENT', DATA.alive?'':'bad');
  html+=card('MRR',inr(f.mrr),'ARR '+inr(f.arr));
  html+=card('Customers',f.active_customers.toLocaleString('en-IN'),'pool '+DATA.pool_size.toLocaleString());
  html+=card('Market share',f.market_share_pct.toFixed(1)+'%','of simulated universe');
  html+=card('Valuation proxy',inr(f.valuation_proxy),'growth-quality multiple');
  html+=card('Churn /mo',(f.logo_churn_pct_monthly??0).toFixed(1)+'%','logo, trailing 30d',
    f.logo_churn_pct_monthly>8?'bad':f.logo_churn_pct_monthly>5?'warn':'good');
  html+=card('CAC',inr(f.cac_blended),'blended trailing 30d');
  html+=card('LTV / CAC',f.ltv_cac==null?'n/a':f.ltv_cac.toFixed(2),
    'LTV '+inr(f.ltv),(f.ltv_cac!=null&&f.ltv_cac>=3)?'good':(f.ltv_cac!=null&&f.ltv_cac<1)?'bad':'');
  html+=card('Gross margin',f.gross_margin_pct.toFixed(0)+'%','');
  html+=card('Runway',last.runway_months>=99?'\u221E':last.runway_months.toFixed(1)+'mo',
    last.runway_months<4?'danger zone':'',last.runway_months<4?'bad':'');
  html+=card('Team',f.headcount+'','founder equity '+(f.founder_equity*100).toFixed(0)+'%');
  html+=card('Quality / debt',f.quality.toFixed(2), 'debt '+Math.round(f.tech_debt));
  html+='</div>';
  html+='<h2>Cash & MRR</h2><canvas id=c_cash></canvas>';
  html+='<h2>Customers & market share</h2><canvas id=c_cust></canvas>';
  html+='<h2>Unit economics</h2><canvas id=c_unit></canvas>';
  html+='<div style="display:flex;gap:10px"><canvas id=c_unit1></canvas><canvas id=c_unit2></canvas></div>';
  return el(html);
};

V.decisions = () => {
  const sc=DATA.decision_scorecard;
  let h=`<h2>Decision scorecard</h2><p>${sc.total} major decisions:
   <span class="pill success">${sc.success} success</span>
   <span class="pill partial">${sc.partial} partial</span>
   <span class="pill fail">${sc.fail} fail</span></p>`;
  h+='<table><tr><th>Day</th><th>Agent</th><th>Kind</th><th>Decision</th><th>Reasoning</th><th>Expected</th><th>Verdict</th></tr>';
  for(const d of [...DATA.decisions].reverse()){
    const exp=Object.entries(d.expected||{}).map(([k,v])=>k+' '+(v>0?'+':'')+v).join(', ');
    const act=d.actual?(typeof d.actual==='object'?JSON.stringify(d.actual):d.actual):'';
    h+=`<tr><td>${d.day}</td><td>${d.agent}</td><td>${d.kind}</td>
      <td style=max-width:280px>${d.decision}<details><summary>actual</summary><pre>${act}</pre></details></td>
      <td style="max-width:300px;color:var(--dim)">${d.reasoning}</td>
      <td>${exp}</td><td><span class="pill ${d.verdict||'untracked'}">${d.verdict||'pending'}</span>
      ${d.lesson?'<details><summary>lesson</summary><pre>'+d.lesson+'</pre></details>':''}</td></tr>`;
  }
  return el(h+'</table>');
};

V.events = () => {
  const evs=[...DATA.company_events.map(e=>({...e,type:'company'})),
             ...DATA.market_events.map(e=>({...e,type:'market'}))]
            .sort((a,b)=>a.day-b.day);
  let h='<h2>History timeline</h2><table><tr><th>Day</th><th>Source</th><th>Event</th></tr>';
  for(const e of evs.slice().reverse()){
    h+=`<tr><td>${e.day}</td><td>${e.type}</td><td>${e.note||e.name}</td></tr>`;
  }
  return el(h+'</table>');
};

V.market = () => {
  let h='<h2>Competitors at end of run</h2><table><tr><th>Name</th><th>Archetype</th><th>Customers</th><th>Quality</th><th>Price mult</th><th>Brand</th><th>Features</th></tr>';
  for(const c of DATA.competitors_final){
    h+=`<tr><td>${c.name}</td><td>${c.archetype}</td><td>${c.customers}</td>
        <td>${c.quality.toFixed(2)}</td><td>x${c.price_mult.toFixed(2)}</td>
        <td>${c.brand.toFixed(2)}</td><td style=color:var(--dim)>${c.features.join(', ')}</td></tr>`;
  }
  h+='</table>';
  h+='<h2>Marketing channels (trailing 30d)</h2><table><tr><th>Channel</th><th>Spend</th><th>Leads</th><th>Observed CPL</th><th>Learned score</th><th>Cumulative spend</th></tr>';
  for(const [k,v] of Object.entries(DATA.channel_summary)){
    h+=`<tr><td>${k}</td><td>${inr(v.spend30)}</td><td>${v.leads30}</td>
        <td>${inr(v.observed_cpl)}</td><td>${v.score}</td><td>${inr(v.cum_spend)}</td></tr>`;
  }
  h+='</table>';
  h+='<h2>Customer pool state</h2><pre>'+JSON.stringify(DATA.customer_states,null,1)+
     '\nTotal universe: '+DATA.pool_size.toLocaleString()+'</pre>';
  return el(h);
};

function mount(){
  document.getElementById('title').textContent =
    `${DATA.name} \u2014 ${DATA.alive?'ALIVE':'DEAD'} @ day ${DATA.days_run}`;
  document.getElementById('subline').textContent =
    `Strategy: ${DATA.strategy} \u00b7 seed ${DATA.config.seed} \u00b7 capital ${inr(DATA.config.starting_capital)} \u00b7 ${DATA.created_utc?.slice(0,10)}` +
    (DATA.death_reason?` \u00b7 ${DATA.death_reason}`:'');
  const tabs=[['overview','Overview'],['decisions','Decisions'],['events','Timeline'],['market','Market']];
  const tabEls=document.getElementById('tabs'), views=document.getElementById('views');
  tabs.forEach(([id,label],i)=>{
    const b=document.createElement('button'); b.textContent=label;
    b.onclick=()=>{ [...tabEls.children].forEach(x=>x.classList.remove('on'));
      b.classList.add('on'); render(id); };
    if(i===0)b.classList.add('on');
    tabEls.appendChild(b);
  });
  function render(id){
    views.innerHTML=''; const node=V[id](); views.appendChild(node);
    if(id==='overview') drawCharts();
  }
  render('overview');
  window.addEventListener('resize',()=>render(
    [...tabEls.children].findIndex(x=>x.classList.contains('on'))===0?'overview':'overview'));
}

function drawCharts(){
  const H=DATA.kpi_series;
  const pts=key=>H.map(s=>[s.day, s[key]]);
  lineChart(document.getElementById('c_cash'),[
    {label:'Cash',color:'#58a6ff',points:pts('cash')},
    {label:'MRR',color:'#3fb950',points:H.map(s=>[s.day,s.mrr])},
  ],{zero:true,fmt:inr});
  lineChart(document.getElementById('c_cust'),[
    {label:'Customers',color:'#d29922',points:pts('active_customers')},
    {label:'Share %',color:'#bc8cff',points:H.map(s=>[s.day,s.market_share_pct])},
  ],{fmt:v=>Math.round(v)});
  lineChart(document.getElementById('c_unit'),[
    {label:'CAC',color:'#f85149',points:pts('cac_blended')},
    {label:'Churn %/mo',color:'#d29922',points:H.map(s=>[s.day,s.logo_churn_pct_monthly])},
  ],{fmt:v=>Math.round(v)});
  lineChart(document.getElementById('c_unit1'),[
    {label:'Brand',color:'#58a6ff',points:H.map(s=>[s.day,(s.brand_awareness*100)])},
  ],{fmt:v=>Math.round(v)+'%'});
  lineChart(document.getElementById('c_unit2'),[
    {label:'Pipeline value',color:'#3fb950',points:pts('pipeline_value')},
  ],{fmt:inr});
}

mount();
</script></body></html>
"""


def generate_dashboard(run_dir: str, out_file: str | None = None) -> str:
    with open(os.path.join(run_dir, "result.json")) as f:
        data = json.load(f)
    name = data.get("name", os.path.basename(run_dir.rstrip("/")))
    html = _TEMPLATE.replace("__DATA__", json.dumps(data)).replace("__RUN_NAME__", name)
    out = out_file or os.path.join(run_dir, "dashboard.html")
    os.makedirs(os.path.dirname(out) or ".", exist_ok=True)
    with open(out, "w") as f:
        f.write(html)
    return out
